### PR TITLE
ENH: supports edm 4 on Linux

### LINKED ISSUE #14: add support for edm 4.x
edm 4.0.0 is available under the rh8-x86_64 path and not rh6-x86_64 like the previous ones. We'll need to add some logic into the shell script for linux to pick the appropriate platform based on the request.

### PR DESCRIPTION
**Pull request by dpinte**
Closes #14

### CODE REVIEW

**Comment by mdickinson** [comment]
@dpinte I'm only seeing changes in the `src/` directory in this PR. I think those changes need to be compiled so that `dist/` is updated, too.

**Comment by rahulporuri** [comment]
https://github.com/enthought/setup-edm-action/blob/f603052ca1dd0704b80cd415143c116296fe9181/DEVELOPING.md has information on how `dist/` can be updated

**Comment by dpinte** [comment]
ha ha, thanks guys! Looking into it.

**Review by mdickinson — APPROVED** [review]
LGTM

**Pull request merged**
